# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rogue
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: doroci

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: doroci's 기술 블로그

description: IT 기술 정리 및 공유를 위한 블로그 입니다.
author:
  name: SoftWare Developer
  email: hiiln0273@gmail.com
  github: doroci
  twitter: none
  pinterest: none
  linkedin: none
  bio: IT 기술 정리 및 공유를 위한 블로그 입니다.
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate